# -------------------- DEPLOYMENT --------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-2
  namespace: microservices
  labels:
    app: microservicio-2
spec:
  selector:
    matchLabels:
      app: microservicio-2
  template:
    metadata:
      labels:
        app: microservicio-2
    spec:
      containers:
        - name: microservicio-2
          image: 628366968712.dkr.ecr.us-east-1.amazonaws.com/tfm_microservice_2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---
# -------------------- SERVICE: LoadBalancer (externo) --------------------
apiVersion: v1
kind: Service
metadata:
  name: microservicio-2
  namespace: microservices
  labels:
    app: microservicio-2
spec:
  type: LoadBalancer
  selector:
    app: microservicio-2
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
# -------------------- SERVICE: ClusterIP (para Prometheus) --------------------
apiVersion: v1
kind: Service
metadata:
  name: microservicio-2-monitor
  namespace: microservices
  labels:
    app: microservicio-2
spec:
  type: ClusterIP
  selector:
    app: microservicio-2
  ports:
    - name: http
      port: 8080
      targetPort: 8080
